on:
  release:
    types:
    - published
name: test published
jobs:
  publish:
    name: publish!!
    runs-on: ubuntu-latest
    steps:
    - name: echo release note
      run: |
        echo "- github.event.release --------------------------"
        echo ${{ github.event.release }}
        echo "- github.event.release.html_url --------------------------"
        echo "${{ github.event.release.html_url }}"
        echo "- github.event.release.name --------------------------"
        echo "${{ github.event.release.name }}"
        echo "- github.event.release.tag_name --------------------------"
        echo "${{ github.event.release.tag_name }}"
        echo "- github.event.release.body --------------------------"
        echo '${{ github.event.release.body }}'
        echo "---------------------------"
        release_body='${{ github.event.release.body }}'
        release_body=${release_body//$'\r\n'/\\n}
        release_body=${release_body//$'\n'/\\n}
        echo "${release_body}"
        echo "---------------------------"
        echo "---------------------------"
